---

- hosts: all
  become: true
  pre_tasks:

  - name: Install updates (OracleLinux)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "OracleLinux"

  - name: Install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: web_servers
  become: true
  tasks:


  - name: Install apache2 and support packages
    tags: apache,apache2,ubuntu
    apt:
      update_cache: yes
      name:
        - apache2
        - libapache2-mod-php 
      state: latest
    when: ansible_distribution == "Ubuntu"




  - name: Install apache2 and support packages
    tags: apache,centos,httpd
    dnf:
      update_cache: yes
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "OracleLinux"

  - name: copy default html file for site
    tags: apache, apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: Install mariadb package (OracleLinux)
    tags: centos,db,mariadb
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "OracleLinux"

  - name: Install mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"


- hosts: file_servers
  become: true
  tasks:

  - name: Install samba package
    tags: samba
    package:
      name: samba
      state: latest
